#Base image
FROM node:20.14.0-alpine

#Set working directory
WORKDIR /app

#Copy package
COPY package*.json ./

#Install dependencies
RUN npm install

#Copy source code
COPY . .

#Build and migrate database
RUN npm run build

#Execute command
CMD ["npm", "start"]